// tools/gen-prompts.mjs — the prompt every agent role receives, snapshotted per engine.
//
// Runs each engine's flow scenarios (tools/flows/<name>.flow.mjs) through tests/harness.mjs and keeps one
// copy of every distinct prompt variant: same role, schema and text once the item id and every number are
// masked, so a variant repeated per block or per round appears once. An edit meant for one mode or round
// that also changes another then shows in the git diff under the variant it leaked into. The suite fails
// while a snapshot is stale, the way it does for FLOW.md.
//
//   node tools/gen-prompts.mjs [<name>...]           # write tests/snapshots/<name>.prompts.md
//   node tools/gen-prompts.mjs [<name>...] --check   # write nothing; exit 1 naming stale snapshots
//   node tools/gen-prompts.mjs <name> --dump <file>  # every distinct (prompt, schema) as JSON, to diff a refactor
//
// Ordinary Node, not an engine: real imports, `node --check` applies.

import { mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { REPO_ROOT, readRoles, runTrace } from '../tests/harness.mjs';
import { loadSpecs } from './gen-flows.mjs';

export const snapshotPath = (name) => join(REPO_ROOT, 'tests', 'snapshots', `${name}.prompts.md`);

/** Every agent call across the spec's scenarios, in scenario order, tagged with its role. */
export async function collectCalls(spec) {
  const roles = readRoles(readFileSync(join(REPO_ROOT, spec.engine), 'utf8'));
  const roleOf = (label) => roles.filter((r) => label.startsWith(r)).sort((a, b) => b.length - a.length)[0] ?? label;
  const calls = [];
  for (const scenario of spec.scenarios) {
    const trace = await runTrace(spec.engine, scenario);
    for (const c of trace.calls) {
      calls.push({ scenario: scenario.name, label: c.label, role: roleOf(c.label), prompt: c.prompt, schema: JSON.stringify(c.opts.schema ?? null, null, 2) });
    }
  }
  return calls;
}

/** A fence longer than any tilde run inside the text, so a prompt holding its own fences stays one block. */
function fence(text) {
  const longest = Math.max(0, ...[...text.matchAll(/~+/g)].map((m) => m[0].length));
  return '~'.repeat(Math.max(4, longest + 1));
}

/** A call's variant key: its role, its schema, and its prompt with the item id and every number masked. */
function variantKey(c) {
  const item = c.label.slice(c.role.length).replace(/[\s:/]+r\d+$/, '').replace(/^[\s:/]+/, '').trim();
  const masked = (item ? c.prompt.split(item).join('<item>') : c.prompt).replace(/\d+/g, 'N');
  return `${c.role}\u0000${c.schema}\u0000${masked}`;
}

/** The snapshot document: the first call of every distinct prompt variant, in scenario order. */
export function renderSnapshot(spec, calls) {
  const firsts = new Map();
  const schemaIndex = new Map();
  const variantCount = new Map();
  for (const c of calls) {
    const key = variantKey(c);
    if (firsts.has(key)) continue;
    const perRole = schemaIndex.get(c.role) ?? new Map();
    if (!perRole.has(c.schema)) perRole.set(c.schema, perRole.size + 1);
    schemaIndex.set(c.role, perRole);
    variantCount.set(c.role, (variantCount.get(c.role) ?? 0) + 1);
    firsts.set(key, { ...c, schemaNo: perRole.get(c.schema), variantNo: variantCount.get(c.role) });
  }
  const entries = [...firsts.values()];

  const out = [
    `# ${spec.name} prompt snapshot`,
    '',
    `Generated by \`node tools/gen-prompts.mjs ${spec.name}\` from \`tools/flows/${spec.name}.flow.mjs\`. Each entry is one`,
    'distinct prompt an agent role receives, first seen in the scenario named. `--check` fails the suite while',
    'this file is stale.',
    '',
    '| Role | Variant | Schema | Prompt chars | First scenario |',
    '|---|---|---|---|---|',
    ...entries.map((e) => `| ${e.role} | ${e.variantNo} | ${e.schemaNo} | ${e.prompt.length} | ${e.scenario.replace(/\|/g, '\\|')} |`),
    '',
  ];
  for (const e of entries) {
    const pf = fence(e.prompt);
    const sf = fence(e.schema);
    out.push(`## ${e.role} · variant ${e.variantNo} · schema ${e.schemaNo}`, '', `\`${e.label}\` in "${e.scenario}"`, '', `${pf}text`, e.prompt, pf, '', `${sf}json`, e.schema, sf, '');
  }
  return out.join('\n');
}

async function main(argv) {
  // Input
  const at = argv.indexOf('--dump');
  const dumpTo = at === -1 ? null : argv[at + 1];
  const rest = at === -1 ? argv : argv.filter((_, i) => i !== at && i !== at + 1);
  const check = rest.includes('--check');
  const names = rest.filter((a) => !a.startsWith('--'));
  const unknown = rest.filter((a) => a.startsWith('--') && a !== '--check');
  if (unknown.length || (at !== -1 && (!dumpTo || names.length !== 1))) {
    console.error('usage: node tools/gen-prompts.mjs [<name>...] [--check] | <name> --dump <file>');
    return 1;
  }
  const specs = await loadSpecs(names);

  // Process
  const stale = [];
  for (const spec of specs) {
    const calls = await collectCalls(spec);
    if (dumpTo) {
      const seen = new Set();
      const distinct = calls.filter((c) => !seen.has(c.prompt + c.schema) && seen.add(c.prompt + c.schema));
      writeFileSync(dumpTo, `${JSON.stringify(distinct, null, 1)}\n`);
      console.log(`dumped ${distinct.length} distinct call(s) of ${spec.name} to ${dumpTo}`);
      continue;
    }
    const text = renderSnapshot(spec, calls);
    const path = snapshotPath(spec.name);
    let current = null;
    try { current = readFileSync(path, 'utf8'); } catch { current = null; }
    const rel = path.slice(REPO_ROOT.length + 1).replace(/\\/g, '/');
    if (check) {
      if (current !== text) stale.push(rel);
      console.log(`${current === text ? 'fresh' : 'STALE'}    ${rel}`);
      continue;
    }
    if (current === text) { console.log(`unchanged ${rel}`); continue; }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
    console.log(`wrote    ${rel}`);
  }

  // Output
  if (stale.length) {
    console.error(`\n${stale.length} stale prompt snapshot(s): ${stale.join(', ')} — run \`node tools/gen-prompts.mjs\` and commit the result.`);
    return 1;
  }
  return 0;
}

// Realpath both sides, as gen-flows does: a link in the script path otherwise made the CLI a silent no-op.
let invokedDirectly = false;
try {
  invokedDirectly = Boolean(process.argv[1])
    && pathToFileURL(realpathSync(process.argv[1])).href === pathToFileURL(realpathSync(fileURLToPath(import.meta.url))).href;
} catch { invokedDirectly = false; }

if (invokedDirectly) {
  let code = 0;
  try {
    code = await main(process.argv.slice(2));
  } catch (e) {
    console.error(e?.message ?? String(e));
    code = 1;
  }
  process.exit(code);
}
